[CHK-3172] remove xpay vpos refs
pagopa/pagopa-ecommerce-local pull request #172
Opened 2024-08-28 14:52 UTC by ciuffagianluca

Remove XPAY VPOS refs

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
  expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-08-28 15:43 UTC, pietro-tota commented on .env
> +ECOMMERCE_TRANSACTIONS_COMMIT_SHA=CHK-3096-remove-xpay-vpos-references
```suggestion
ECOMMERCE_TRANSACTIONS_COMMIT_SHA=main
```

2024-08-28 15:43 UTC, pietro-tota commented on .env
> +ECOMMERCE_EVENT_DISPATCHER_COMMIT_SHA=CHK-3136-delete-xpay-vpos-refs
```suggestion
ECOMMERCE_EVENT_DISPATCHER_COMMIT_SHA=main
```

2024-08-28 15:45 UTC, pietro-tota commented on pgs-mock/Dockerfile.pgs-mock
> -FROM node:18.19.0-alpine
delete `pagopa-pgs-mock` from docker-compose.yaml file too

2024-08-28 15:45 UTC, giovanniberti commented on .env
> +ECOMMERCE_TRANSACTIONS_COMMIT_SHA=CHK-3096-remove-xpay-vpos-references
TODO change back to `main`

2024-08-28 15:45 UTC, giovanniberti commented on .env
> +ECOMMERCE_EVENT_DISPATCHER_COMMIT_SHA=CHK-3136-delete-xpay-vpos-refs
TODO change back to `main`

2024-08-28 15:46 UTC, giovanniberti submitted a review, later dismissed

2024-08-28 15:49 UTC, pietro-tota commented on pgs-mock/Dockerfile.pgs-mock
> -FROM node:18.19.0-alpine
delete pagopa-pgs-mock from docker-compose.yaml file too, as for now docker compose build is broken for missing still referenced Dockerfile

2024-08-28 15:49 UTC, pietro-tota requested changes
Please remove pgs mock from docker-compose-yaml file

2024-08-29 07:18 UTC, pietro-tota approved these changes

2024-09-05 07:26 UTC, petretiandrea approved these changes

2024-09-05 11:44 UTC, merged